export const GET_ALL_MOVIES = "GET_ALL_MOVIES";
export const GET_ALL_MOVIES_SUCCESS = "GET_ALL_MOVIES_SUCCESS";
export const GET_ALL_MOVIES_FAILURE = "GET_ALL_MOVIES_FAILURE";

export const GET_ALL_UPCOMMINGS = "GET_ALL_UPCOMMINGS";
export const GET_ALL_UPCOMMINGS_SUCCESS = "GET_ALL_UPCOMMINGS_SUCCESS";
export const GET_ALL_UPCOMMINGS_FAILURE = "GET_ALL_UPCOMMINGS_FAILURE";

export const GET_ALL_TRENDINGS = "GET_ALL_TRENDINGS";
export const GET_ALL_TRENDINGS_SUCCESS = "GET_ALL_TRENDINGS_SUCCESS";
export const GET_ALL_TRENDINGS_FAILURE = "GET_ALL_TRENDINGS_FAILURE";

export const GET_ALL_TVSHOWS = "GET_ALL_TVSHOWS";
export const GET_ALL_TVSHOWS_SUCCESS = "GET_ALL_TVSHOWS_SUCCESS";
export const GET_ALL_TVSHOWS_FAILURE = "GET_ALL_TVSHOWS_FAILURE";

export const GET_ALL_PEOPLE = "GET_ALL_PEOPLE";
export const GET_ALL_PEOPLE_SUCCESS = "GET_ALL_PEOPLE_SUCCESS";
export const GET_ALL_PEOPLE_FAILURE = "GET_ALL_PEOPLE_FAILURE";

export const GET_MOVIE_DETAILS = "GET_MOVIE_DETAILS";
export const GET_MOVIE_DETAILS_SUCCESS = "GET_MOVIE_DETAILS_SUCCESS";
export const GET_MOVIE_DETAILS_FAILURE = "GET_MOVIE_DETAILS_FAILURE";

export const GET_TVSHOWS_DETAILS = "GET_TVSHOWS_DETAILS";
export const GET_TVSHOWS_DETAILS_SUCCESS = "GET_TVSHOWS_DETAILS_SUCCESS";
export const GET_TVSHOWS_DETAILS_FAILURE = "GET_TVSHOWS_DETAILS_FAILURE";

export const GET_PEOPLE_DETAILS = "GET_PEOPLE_DETAILS";
export const GET_PEOPLE_DETAILS_SUCCESS = "GET_PEOPLE_DETAILS_SUCCESS";
export const GET_PEOPLE_DETAILS_FAILURE = "GET_PEOPLE_DETAILS_FAILURE";

export const GET_MOVIES_REVIEW = "GET_MOVIES_REVIEW";
export const GET_MOVIES_REVIEW_SUCCESS = "GET_MOVIES_REVIEW_SUCCESS";
export const GET_MOVIES_REVIEW_FAILURE = "GET_MOVIES_REVIEW_FAILURE";

export const TVSHOW_REVIEW = "TVSHOW_REVIEW";
export const TVSHOW_REVIEW_SUCCESS = "TVSHOW_REVIEW_SUCCESS";
export const TVSHOW_REVIEW_FAILURE = "TVSHOW_REVIEW_FAILURE";

export const SEARCH = "SEARCH";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
